version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Passw0rd
    ports:
      - 27017:27017
    volumes:
      - ./data/:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Passw0rd
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: Passw0rd
      ME_CONFIG_MONGODB_URL: mongodb://root:Passw0rd@mongodb:27017/
  api:
    image: 'simoncarr/pulumi_automation_api:latest'
    ports:
      - '3000:3000'
    environment:
      - mongodb_username=root
      - mongodb_password=Passw0rd
      - mongodb_url=mongodb://mongodb
      - mongodb_port=27017
      - mongodb_dbname=infrastructure
      - mongodb_authsource=admin

  gui:
    image: 'simoncarr/pulumi_automation_gui:latest'
    ports:
      - '8085:8080'
    environment:
      - VUE_APP_API_URL=http://api:3000
